- name: Install Nginx For Demo CloudFormation - Meetup AWS User Group 
  hosts: demo

  tasks:
    - name: Update Packages in Ubuntu - Meetup AWS User Group
      become: yes
      shell: apt-get update

    - name: Install Nginx For Demo 1 - Meetup AWS User Group
      become: yes
      shell: apt-get install nginx -y

    - name: Downloading Template Html - Meetup AWS User Group
      become: yes
      get_url: url=https://s3.amazonaws.com/stackaws-meetups/AWSUserGroups/22-06-2017/demo-1/html.zip  dest=/opt/ mode=0444
    
    - name: Install UNZIP - Meetup AWS User Group
      become: yes
      shell: apt-get install unzip -y

    - name: Decompress Folder Template Html - Meetup AWS User Group
      become: yes
      shell: unzip /opt/html.zip -d /opt/

    - name: Coping Folder Template Html to Folder Nginx - Meetup AWS User Group
      become: yes
      shell: cp -R /opt/html/* /usr/share/nginx/html/